version: '3.8'

services:
  mongo:
    image: mongo:7.0.11
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpw
    restart: unless-stopped

  urlservice:
    image: soserdev/shortener-urlservice:latest  # Built from your Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - mongo
    environment:
      SERVER_PORT: 8080
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017
    restart: unless-stopped
