# Example of custom Java runtime using jlink in a multi-stage container build
FROM eclipse-temurin:21 as build

# Create a custom Java runtime
RUN $JAVA_HOME/bin/jlink \
         --add-modules java.base,java.logging,java.naming,java.desktop,jdk.unsupported \
         --strip-debug \
         --no-man-pages \
         --no-header-files \
         --compress=2 \
         --output /javaruntime

# Define your base image
FROM debian:buster-slim
ENV JAVA_HOME=/opt/java/openjdk
ENV PATH "${JAVA_HOME}/bin:${PATH}"
COPY --from=build /javaruntime $JAVA_HOME

# Continue with your application deployment
RUN mkdir /opt/app
COPY ../target/*.jar /opt/app/application.jar
CMD ["java", "-jar", "/opt/app/application.jar"]