# Example of custom Java runtime using jlink in a multi-stage container build
FROM eclipse-temurin:21 as build

# Create a custom Java runtime
RUN $JAVA_HOME/bin/jlink \
         --add-modules java.xml,java.sql,java.prefs,java.desktop \
         --strip-debug \
         --no-man-pages \
         --no-header-files \
         --compress=2 \
         --output /springboot-runtime

# FROM alpine:latest
FROM debian:buster-slim
COPY --from=build  /springboot-runtime /opt/jdk
ENV PATH=$PATH:/opt/jdk/bin
# EXPOSE 8080
COPY ../target/*.jar /opt/app/application.jar
CMD ["java", "-showversion", "-jar", "/opt/app/application.jar"]