# application-production.properties are activated in kubernetes api.yaml
spring.application.name=UrlService
server.port=8080

spring.data.mongodb.auto-index-creation=true

spring.mongodb.host=mongodb.databases
spring.mongodb.port=27017
spring.mongodb.database=urlservice
spring.mongodb.username=root
spring.mongodb.password=rootpw
spring.mongodb.authentication-database=admin

spring.web.error.include-stacktrace=never

# Expose actuator endpoints
management.endpoints.web.exposure.include=health,info
# Enable Kubernetes-style probes
management.endpoint.health.probes.enabled=true
# Show health details (optional but helpful)
management.endpoint.health.show-details=always
